
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
- jekyll-remote-theme

# Activate LaTeX math rendering
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      math: true
